### ISSUE TITLE
[bug] blc_configure.sh: No such file or directory.

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#112]
@travisdoor There is not file `blc_configure.sh` in your project (repository).

**Comment by travisdoor** [comment]
Do you use master version or downloaded release package?

**Comment by ghost** [comment]
@travisdoor master version

**Comment by travisdoor** [comment]
In such case you should manually execute setup script in `install` directory depending on platform you use. This should be probably also described in docs.

**Comment by travisdoor** [comment]
This script only generate default config file.
