### ISSUE TITLE
[implement] i++ and i-- for int and float.

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#114]
@travisdoor I think it will be better if you add `i++/++i` as alternative to `i += 1` and `i--/--i` as alternative to `i -= 1`:

```c
i := 0
i++ // i = 1
++i // i = 2
i-- // i = 1
--i // i = 0
```

**Comment by travisdoor** [comment]
Those can be eventually implemented as syntactic sugar but it has very low priority in my opinion. I'm not sure if this additional complexity is really needed, += and -= are more explicit in this case I guess...
