### ISSUE TITLE
[bug] Segmentation fault on #entry (must be fixed)

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#116]
@travisdoor 

**code:**

```c
#entry program

program :: fn () s32 {
        return 0;
}
```

**result:**

```
Compiler version: 0.7.2, LLVM: 10
Compile assembly: out [DEBUG]
Target: x86_64-apple-darwin17.7.0
Segmentation fault: 11
```

**Comment by travisdoor** [comment]
`#entry program` in this case compiler should complain about invalid syntax, and eventually documentation should be more descriptive about hash directive usage (add examples).
