### ISSUE TITLE
[bug] Using void function.

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#119]
@travisdoor Looks like another error:

**code:**

```
main :: fn() { 
    print("Hello, world!");
}
```

**output:**

```
Compiler version: 0.7.2, LLVM: 10
Compile assembly: out [DEBUG]
Target: x86_64-apple-darwin17.7.0
/Users/t0md3an/lib/bl/api/os/macos.bl:308:12 Invalid cast from 'void' to 's32'.
> 308 |     out :: cast(s32) main();
      |            ^^^^
  309 | 
Compiled 4298 lines in 0.029341 seconds.
There were errors, sorry...

Finished at 04-10-2020 16:49:33
```

**Comment by travisdoor** [comment]
This is not bug, `main` **must** return `s32` value. Documentation is not clear (maybe outdated) in this case, I already created task for it.  https://github.com/travisdoor/bl/issues/118

**Comment by travisdoor** [comment]
There should be possibility to define void returning main in future

**Comment by travisdoor** [comment]
http://biscuitlang.org/versions/0.7.2/examples/001_first_program.bl.html
