### ISSUE TITLE
[add] #entry documentation

### ISSUE THREAD

**Issue by ghost** [biscuitlang/bl#120]
@travisdoor How to use `#entry`?

**Comment by travisdoor** [comment]
There is no need to use it, it's more like compiler internal directive to mark function as entry point. Such function is already defined in platform specific preload file: https://github.com/travisdoor/bl/blob/aff2b577d57c21745ecb26686603093df8b401e1/lib/bl/api/os/macos.bl#L290

It basically call user defined `main` function (s32 return value is mandatory here).

```
main :: fn () s32 {
    return 0;
}
```
