### ISSUE TITLE
Slow intrepreter

### ISSUE THREAD

**Issue by cairdac-rd** [biscuitlang/bl#56]
Hello,
I'm making some benchmarks to compare the speed execution of some interpreted languages [here](https://github.com/cairdac-rd/script-language-fibo-benchmarks/) :

the script source "test_fib.bl" is :

```
#load "std/core.bl"
main :: fn ()  {
print("%\n",fib(36));
};

fib :: fn (n: s32) s32 {
  if n < 2 {
    return n;
  } else {
    return fib(n-1) + fib(n-2);
  }
  return -1;
};

```

The code compiles well and the generated executable is very fast.

```
$ bin/blc  examples/test_fib.bl
Compiler version: 0.4.1 (pre-alpha)
Target: x86_64-pc-linux-gnu
Compile assembly: test_fib
Running native linker...
Compiled 455 lines in 0.093750 seconds.
```

```
$ time ./test_fib
14930352

real    0m0.062s
user    0m0.063s
sys     0m0.000s
```

But running the script directly is very slow compared to other script languages using LLVM as a back-end :
```
$ bin/blc -r  examples/test_fib.bl
Compiler version: 0.4.1 (pre-alpha)
Target: x86_64-pc-linux-gnu
Compile assembly: test_fib

Executing 'main' in compile time...
14930352
Execution finished without errors

Running native linker...
Compiled 455 lines in 8.890625 seconds.
```

Regards,

**Comment by travisdoor** [comment]
Hi,

first of all thank you for your benchmark test; bl interpreter is just an extension mainly used for execution of compile time blocks of code during compilation process or testing during development. It is not supposed to be fast for now, we are still focusing on compiled executables... General performance of compiler and compile time execution will be improved later when all language features will be finished.

br

**Comment by travisdoor** [comment]
btw we don't use LLVM JIT for compile time execution
http://biscuitlang.org/MIR.html#org51a4dc4

**Comment by cairdac-rd** [comment]
Hi,
thank you for your feedback.
Very clear now. I thought that LLVM Jit was used for execution also.
